command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.address
  - "0.0.0.0"
  - --server.enableCORS
  - "false"
  - --server.enableXsrfProtection
  - "false"

env:
  - name: DATABRICKS_HOST
    value: "https://dbc-0726d26f-3749.cloud.databricks.com"
  - name: ENDPOINT_NAME
    value: "agents_boopatt-job_finder"
  - name: SQL_WAREHOUSE_ID
    value: "1c9c842c6ceae014"
